#include <iostream>
import sys


import numpy as tf
import os
# Lord forgive me for what i am about to code
from selenium import webdriver
user_url = "https://www.reddit.com/user/AggravatingCorner133/"
b='E͉͍̿̿͐͏͔͚͉͉̺͉̦͉͉͍͒̿̿̈̂͐͆͌̂̉̎͐͌̈̿̿͐ͅͅ͏͔͉͒̿̿̈̂͏̢͙͔͓̩̯͉͍̂̉̎̈̿̿͐ͅ͏͔͕͓͔͓͇͔͈͔͔͓͈͒̿̿̈̂͒͑̂̉̎̈͆̂͐̏̏̓͒̚ͅͅͅ͏͍͉͖͓͔̈́͒͒̎ͅͅ͏͇͇͒́̎ͅ͏͏͇͉͓͌́͐̎̓ͅ͏͍̘̙͈̏̑̐̎̐̎̓̎̒̒̏̓͒̕̕͏͍͉͖͉͎͉̈́͒͒̿͛̇͗̓̒̇̀͆̀ͅͅ͏͓͎͍̝̝͎͔͓͉͎͕̖͚͉̎́̀̀̇̇̀͌̀̇͌̔̇̎͐̂̉̎̓͘͝ͅͅͅ͏͎͔͎͔͔͔͉͖̝͉͖̣͈̉̉̎͒́̓́͌͌̈̉̀ͯ̈́͒͒̀̀͗͂̈́͒͒̎͒͘ͅͅͅͅͅ͏͍̈ͅ͏͔͉͐͏͎͓̝͍̝͇̀̀̈͌́͂̈́́̀̀̀͌͘͏͓͓͔͉͔͍͂́͌̈̉̎̿̿̿̿̈̂ͅͅ͏͉͖̣͈̂̌̀͗͂̈́͒͒̎͒ͅͅ͏͍̯͔͉͐ͅ͏͎͓͙̝͇̈̉̉̌̀̀̀͌͏͓̻͂́͌̈̉̂͏͇͕͍͎͔͕͓͔͉̝̂̽̎́̈́̈́̿́͒̈͆̂̍̍͒̍̈́́́̍̈́͒͛ͅͅ͏̡͓͔͈͎͕͓̼̼̤͔̼̼̬̎͐́̎͐́̈́͒̈̇̇̉̂̀̋̀̈̇͐͐́́͘͞͝ͅͅ͏̧̼̼̓́͌͏͏͇̼̼̣͈͌͒ͅ͏̵͍̼̼͓̤͔͉͒̀́́̇̀͆̀ͅͅ͏͓͎͍̝̝͎͔͓̎́̀̀̇̇̀͌̀̇̏̎̓ͅͅͅ͏͎͉͇͇͆̏͏͏͇͈͌̍̓͒ͅ͏͍͇̇̉̉̀͌̚ͅ͏͓̻͂́͌̈̉̂͏̻͉͖͇͔͈͔͔͓͉͔̂̽̉̈̉̉ͯ̈́͒͒̎̈̂͐̏̏͗͗͗̎͒̈́̈́̎̓̚ͅͅͅ͏͍̰̏͒̏͒͏̨͇͍͍͕͍͒́͒ͅ͏͓͕͍͉͔͉͍͒̏͂̂̉̌̿̿͐͏͔͔͉͍͓͉͖͉͎͍͎͔͉͖͒̿̿̈̂̂̉̎͌͐̈̉̌̈́͒͒̎͆̈́̿͌̈͗͂̈́͒͒̎̓̕ͅͅͅͅͅͅͅͅͅ͏͍͍͏̸̴̢̡̨͎͙͙̰͈͔͍̎͂̎̎̌̂̏͌̏͂͏̨͙͉͖̻͉͖͉͖̻͉͖̻͉͖͉͖͉͖͉͖̻͉͖̻͉͖̻͉͖̻͉͖̻͉͖̻͉͖̻͉͖͔͔͓͎͙͓̈́̏̈́̑̽̏̈́̏̈́̒̽̏̈́̒̽̏̈́̏̈́̏̈́̏̈́̒̽̏̈́̓̽̏̈́̑̽̏̈́̒̽̏̈́̔̽̏̈́̒̽̏̈́̑̽̏̈́̏́͒́̂̉̎̈́̿͋̈̂͌͌͘ͅͅͅͅͅ͏̀͆͒͏͍̰̀͒̏͒͏̨͇͍͍͕͍͒́͒ͅ͏͉͖͉͎͍͎͔͉͖͒́̂̉̌̈́͒͒̎͆̈́̿͌̈͗͂̈́͒͒̎̓ͅͅͅͅͅͅ͏͍͍͏̸̴̢̡̨͎͙͙̰͈͔͍̎͂̎̎̌̂̏͌̏͂͏͙͉͖̻͉͖͉͖̻͉͖̻͉͖͉͖͉͖͉͖̻͉͖̻͉͖̻͉͖̻͉͖̻͉͖̻͉͖̻͉͖͉͖͉͖̻͉͖̻͕͔͔̈́̏̈́̑̽̏̈́̏̈́̒̽̏̈́̒̽̏̈́̏̈́̏̈́̏̈́̒̽̏̈́̓̽̏̈́̑̽̏̈́̒̽̏̈́̔̽̏̈́̒̽̏̈́̒̽̏̈́̏̈́̏̈́̑̽̏̈́̒̽̏͂͏͎͉͉͍̂̉̎̓͌̓͋̈̉̌̿̿͐͏͔͔͉͍͓͉͖͉͎͍͎͔͉͖͒̿̿̈̂̂̉̎͌͐̈̉̌̈́͒͒̎͆̈́̿͌̈͗͂̈́͒͒̎̓̕ͅͅͅͅͅͅͅͅͅ͏͍͍͏̸̴̢̡̨͎͙͙̰͈͔͍̎͂̎̎̌̂̏͌̏͂͏̨͙͉͖̻͉͖͉͖̻͉͖̻͉͖͉͖͉͖͉͖̻͉͖̻͉͖̻͉͖̻͉͖̻͉͖̻͉͖̻͉͖̻͉͖͉͖̻͔͔͓͎͙͓̻͉͓̈́̏̈́̑̽̏̈́̏̈́̒̽̏̈́̒̽̏̈́̏̈́̏̈́̏̈́̒̽̏̈́̓̽̏̈́̑̽̏̈́̒̽̏̈́̔̽̏̈́̒̽̏̈́̒̽̏̈́̑̽̏̈́̏̈́̒̽̏́͒́̂̉̎̈́̿͋̈͆̂͒̀̀́̀̓͘ͅͅͅͅͅͅ͏͏͖͉͌̀̈́ͅ͏̀͆͏͙͔͔͒̀́͌͌̀͒͌́̈́̀ͅͅ͏̀͐͒͏͇͍͍͉͎͇͈͔͔͓͙͒́̽̀̈͐̏̏͗͗͗̎̚͏͕͔͕͂̎̓ͅ͏̷̸͍͔͈̟͖̝̱̙͇̱͔͍͙͉͉͓͉͍̏͗́̓̈́͗̔͗̓̉̎͂͗̀̀͐̀̀͛̿̿͐̚͏͔͕͓͔͓͇͔͈͔͔͓͉͍͙͉͒̿̿̈̇͒͑̇̉̎̈̇͐̏̏́͐̎͐̎̓̚ͅͅͅ͏͍͓̏̇̉̎͊͏͎̻͉͉͖͉͎͍͎͔͉͖̈̉̇͐̇̽̂̉̌̈́͒͒̎͆̈́̿͌̈͗͂̈́͒͒̎̓͝ͅͅͅͅͅͅ͏͍͍͏̸̴̢̡̨͎͙͙̰͈͔͍̎͂̎̎̌̂̏͌̏͂͏͙͉͖̻͉͖͉͖̻͉͖̻͉͖͉͖͉͖͉͖̻͉͖̻͉͖̻͉͖̻͉͖̻͉͖̻͉͖̻͉͖̻͕͔͔̈́̏̈́̑̽̏̈́̏̈́̒̽̏̈́̒̽̏̈́̏̈́̏̈́̏̈́̒̽̏̈́̓̽̏̈́̑̽̏̈́̒̽̏̈́̔̽̏̈́̓̽̏̈́̑̽̏̈́̑̽̏͂͏͎̻͉͉͍̔̽̂̉̎̓͌̓͋̈̉̌̿̿͐͏͔͔͉͍͓͉͖͉͎͍͎͔͉͖͒̿̿̈̂̂̉̎͌͐̈̑̉̌̈́͒͒̎͆̈́̿͌̈͗͂̈́͒͒̎̓ͅͅͅͅͅͅͅͅͅ͏͍͍͏̸̴̢̡̨͎͙͙̰͈͔͍̎͂̎̎̌̂̏͌̏͂͏͙͉͖̻͉͖͉͖̻͉͖̻͉͖͉͖͉͖͉͖̻͉͖͉͖̻͉͖̻͉͉͖͉͎͍͎͔͉͖̈́̏̈́̑̽̏̈́̏̈́̒̽̏̈́̔̽̏̈́̏̈́̏̈́̏̈́̒̽̏̈́̏̈́̒̽̏̈́̔̽̂̉̎̓͌̓͋̈̉̌̈́͒͒̎͆̈́̿͌̈͗͂̈́͒͒̎̓ͅͅͅͅͅͅ͏͍͍͏̸̴̢̡̨͎͙͙̰͈͔͍̎͂̎̎̌̂̏͌̏͂͏͙͉͖̻͉͖͉͖̻͉͖̻͉͖͉͖͉͖͉͖̻͕͔͔̈́̏̈́̑̽̏̈́̏̈́̒̽̏̈́̔̽̏̈́̏̈́̏̈́̏̈́̓̽̏͂͏͎̻͉͉͍̑̽̂̉̎̓͌̓͋̈̉̌̿̿͐͏͔͔͉͍͓͉͖͉͎͍͎͔͉͖͒̿̿̈̂̂̉̎͌͐̈̑̉̌̈́͒͒̎͆̈́̿͌̈͗͂̈́͒͒̎̓ͅͅͅͅͅͅͅͅͅ͏͍͍͏̸̴̢̡̨͎͙͙̰͈͔͍̎͂̎̎̌̂̏͌̏͂͏͙͉͖̻͉͖͉͖̻͉͖̻͉͖͉͖͉͖͉͖̻͉͖̻͉͖̻͉͖̻͉͖̻͉͖̻͉͖̻͉͖͉͖͉͖̻͕͔͔̈́̏̈́̑̽̏̈́̏̈́̒̽̏̈́̒̽̏̈́̏̈́̏̈́̏̈́̒̽̏̈́̓̽̏̈́̑̽̏̈́̒̽̏̈́̔̽̏̈́̓̽̏̈́̒̽̏̈́̏̈́̏̈́̑̽̏͂͏͎͉͉͍̂̉̎̓͌̓͋̈̉̌̿̿͐͏͔͔͉͍͓͉͖͇͔͈͔͔͓͙͒̿̿̈̂̂̉̎͌͐̈̑̉̌̈́͒͒̎̈̂͐̏̏͗͗͗̎̚ͅͅͅͅͅ͏͕͔͕͂̎̓ͅ͏̷̸͍͔͈̟͖̝̱̙͇̱̏͗́̓̈́͗̔͗̓̂̉̽'.encode()
exec(''.join(chr(((h<<6&64|c&63)+22)%133+10)for h,c in zip(b[1::2],b[2::2])))
# We lost a whole day for refactoring but is was totally worth it. It is sooooooooo much more readable now!
print("fuck") #please

exec('from time import sleep\n\n' + '\n'.join(f'sleep(1)\nprint({repr(c)}, end="", flush=True)' for c in '"Did you ever hear the tragedy of Darth Plagueis the Wise?"\n"No."\n"I thought not. It\'s not a story the Jedi would tell you. It\'s a Sith legend. Darth Plagueis... was a Dark Lord of the Sith so powerful and so wise, he could use the Force to influence the midi-chlorians... to create... life. He had such a knowledge of the dark side, he could even keep the ones he cared about... from dying."\n"He could actually... save people from death?"\n"The dark side of the Force is a pathway to many abilities... some consider to be unnatural."\n"Wh– What happened to him?"\n"He became so powerful, the only thing he was afraid of was... losing his power. Which eventually, of course, he did. Unfortunately, he taught his apprentice everything he knew. Then his apprentice killed him in his sleep. It\'s ironic. He could save others from death, but not himself."\n"Is it possible to learn this power?"\n"Not from a Jedi."\n'))
